// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col items-center justify-center h-full space-y-8 text-center relative overflow-hidden\"><!-- Spicy Mode Background Effects --><div class=\"absolute inset-0 pointer-events-none overflow-hidden\" x-show=\"theme === 'rhcp'\" style=\"display: none;\"><div class=\"spicy-bg-pattern absolute top-0 left-0 w-full h-full opacity-10\"></div><div class=\"spicy-floating-item item-1 absolute top-10 left-10 w-32 h-32 rounded-full blur-3xl bg-marigold opacity-20 animate-pulse\"></div><div class=\"spicy-floating-item item-2 absolute bottom-20 right-20 w-40 h-40 rounded-full blur-3xl bg-pink-hot opacity-20 animate-pulse delay-700\"></div></div><h1 class=\"text-5xl md:text-7xl font-serif spicy-decoration spicy-home-title relative z-10\" style=\"color: var(--color-text-primary);\">Capturing <span class=\"block italic\" style=\"color: var(--color-text-secondary);\">Moments</span></h1><p class=\"max-w-xl leading-relaxed relative z-10\" style=\"color: var(--color-text-secondary);\">Welcome to my digital gallery. I explore the world through my lens, focusing on landscapes, wildlife, and portraits.</p><div class=\"pt-8 relative z-10\"><a href=\"/portfolio\" class=\"px-8 py-3 border hover:opacity-70 transition-all duration-300 uppercase tracking-widest text-sm inline-block\" style=\"border-color: var(--color-border); color: var(--color-text-primary);\">View Portfolio</a></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Personal Website").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
